FROM mcr.microsoft.com/dotnet/aspnet:10.0-noble-arm32v7 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/Authentication/Microsoft"
RUN dotnet restore "IT.WebServices.Authentication.Services.Microsoft.csproj"
RUN rm -f appsettings.Development.json
RUN dotnet build "IT.WebServices.Authentication.Services.Microsoft.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IT.WebServices.Authentication.Services.Microsoft.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "IT.WebServices.Authentication.Services.Microsoft.dll"]
