FROM mcr.microsoft.com/dotnet/aspnet:8.0-noble-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/Services/Combined"
RUN dotnet restore "IT.WebServices.Services.Combined.csproj"
RUN rm -f appsettings.Development.json
RUN dotnet build "IT.WebServices.Services.Combined.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IT.WebServices.Services.Combined.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "IT.WebServices.Services.Combined.dll"]
